import fs from 'node:fs';import path from 'node:path';
const DIR='fdao-monitor/data',FDAO='0xc5424eb1061bd9e147788c527c95ac27710bfa41';fs.mkdirSync(DIR,{recursive:true});
const ST=['0x3e451024d3d4ca4a6f8985802ef8887d16b5f1b2c495e5ace458437b21d18505','0x05a5b88949c1b7e7b6f52ca8bb014e695c3f9bc8893e0f75a3699a1519507e5c','0x95b92b7b8f8d5c56d72e536e955714d166392387f565da17b314fbb8e73280a1'];
const UN=['0x9d4ddcf7be95a56327247eeb36efb79783c00d13defcd5a572d1e3e0d8bf57d5','0x7baf0db25f935f5cb985caf351c40c4ecfd6a3b4ee3c8e3360183b8f051ed97e','0xc4915ee1bfb9fe5fca0991eeb563dea7da3fe05fb9265ffc22a49c16cc9ff58e'],ALL=[...ST,...UN];
const ENDPOINTS=['https://bsc-rpc.blockreq.com/v1/rpc/public','https://public.1rpc.io/bnb','https://bsc.drpc.org'];const wait=m=>new Promise(r=>setTimeout(r,m));const hx=n=>'0x'+BigInt(n).toString(16),unit=h=>Number(BigInt(h))/1e18,num=h=>Number(BigInt(h)),words=d=>{let s=d.slice(2),a=[];for(let i=0;i<s.length;i+=64)a.push('0x'+s.slice(i,i+64));return a},who=t=>'0x'+t.slice(-40).toLowerCase();
const read=(f,x)=>{try{return JSON.parse(fs.readFileSync(path.join(DIR,f),'utf8'))}catch{return x}},write=(f,x)=>fs.writeFileSync(path.join(DIR,f),JSON.stringify(x,null,2)+'\n');
async function rpc(url,method,params){let r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});let j=await r.json();if(j.error)throw Error(j.error.message||'rpc');return j.result}
async function logs50(from,to){let out=[];for(let a=from;a<=to;a+=50){let b=Math.min(to,a+49),ok=false,last;for(let url of ENDPOINTS){try{out.push(...await rpc(url,'eth_getLogs',[{address:FDAO,fromBlock:hx(a),toBlock:hx(b),topics:[ALL]}]));ok=true;break}catch(e){last=e}}if(!ok)throw last;await wait(80)}return out}
async function logsWide(from,to){for(let url of [ENDPOINTS[0],ENDPOINTS[2]]){try{return await rpc(url,'eth_getLogs',[{address:FDAO,fromBlock:hx(from),toBlock:hx(to),topics:[ALL]}])}catch{}}return logs50(from,to)}
function parse(l){let topic=l.topics[0].toLowerCase(),w=words(l.data),user=who(l.topics[1]),id=l.transactionHash+':'+l.logIndex,block=num(l.blockNumber);if(ST.includes(topic))return{kind:'stake',id,user,block,tx:l.transactionHash,lp:unit(w[0]),meta:unit(w[1]),ts:num(w.at(-1))};return{kind:'unstake',id,user,block,tx:l.transactionHash,lp:unit(w[0]),token:unit(w[2]),fee:unit(w[3]),ts:num(w.at(-1))}}
function hkDate(ts){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Hong_Kong',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(ts*1000))}
let cur=read('current.json',null);if(!cur)throw Error('current.json missing');let state=read('history-state.json',{cursor:cur.indexing.dayStartBlock-1,floor:112795756,events:[],done:false});if(!state.done){let to=state.cursor,from=Math.max(state.floor,to-20000+1),ls=await logsWide(from,to),ids=new Set(state.events.map(e=>e.id));for(let l of ls){let e=parse(l);if(!ids.has(e.id)){state.events.push(e);ids.add(e.id)}}state.cursor=from-1;if(from<=state.floor)state.done=true;}
let all=[...state.events];let todayState=read('state.json',{});for(let e of (todayState.dayEvents||[]))if(!all.some(x=>x.id===e.id))all.push(e);all.sort((a,b)=>a.ts-b.ts);
let first=new Map();for(let e of all)if(e.kind==='stake'&&!first.has(e.user))first.set(e.user,hkDate(e.ts));let m=new Map();for(let e of all){let d=hkDate(e.ts);if(!m.has(d))m.set(d,{date:d,stakeWalletSet:new Set(),newWalletSet:new Set(),stakeCount:0,stakeMeta:0,unstakeCount:0,unstakeToken:0});let x=m.get(d);if(e.kind==='stake'){x.stakeWalletSet.add(e.user);if(first.get(e.user)===d)x.newWalletSet.add(e.user);x.stakeCount++;x.stakeMeta+=e.meta}else{x.unstakeCount++;x.unstakeToken+=e.token}}
let price=Number(cur.market.metaPrice||0);let daily=[...m.values()].map(x=>({date:x.date,stakeWallets:x.stakeWalletSet.size,newWallets:x.newWalletSet.size,stakeCount:x.stakeCount,stakeMeta:x.stakeMeta,stakeUsdAtCurrentPrice:x.stakeMeta*price,unstakeCount:x.unstakeCount,unstakeToken:x.unstakeToken,unstakeUsdAtCurrentPrice:x.unstakeToken*price,netUsdAtCurrentPrice:(x.stakeMeta-x.unstakeToken)*price})).sort((a,b)=>a.date.localeCompare(b.date));
let vals=daily.map(x=>x.stakeUsdAtCurrentPrice),ws=daily.map(x=>x.stakeWallets),avg=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0,last3=avg(vals.slice(-3)),prev3=avg(vals.slice(-6,-3)),w3=avg(ws.slice(-3)),wp3=avg(ws.slice(-6,-3)),flowTrend=prev3?last3/prev3:null,walletTrend=wp3?w3/wp3:null;let trendRisk='数据不足';if(flowTrend!==null){trendRisk=flowTrend<.6?'红色：新增资金动能较前3日下降40%以上':flowTrend<.85?'黄色：新增资金动能明显放缓':flowTrend>1.15?'绿色：新增资金动能仍在增强':'黄色：新增资金大致持平'}
let out={updatedAt:new Date().toISOString(),backfillDone:state.done,coverage:Math.max(0,Math.min(1,(cur.indexing.dayStartBlock-state.cursor)/(cur.indexing.dayStartBlock-state.floor))),firstObservedDate:daily[0]?.date||null,totalObservedStakeWallets:new Set(all.filter(e=>e.kind==='stake').map(e=>e.user)).size,trend:{last3AvgStakeUsd:last3,previous3AvgStakeUsd:prev3,flowRatio:flowTrend,last3AvgWallets:w3,previous3AvgWallets:wp3,walletRatio:walletTrend,risk:trendRisk},daily};write('history-state.json',state);write('history-daily.json',out);console.log(JSON.stringify({ok:true,cursor:state.cursor,done:state.done,events:all.length,days:daily.length,trend:out.trend},null,2));